/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOrdenesRouteImport } from './routes/_authenticated/ordenes'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPreventivoRouteImport } from './routes/_authenticated/preventivo'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedActivosIndexRouteImport } from './routes/_authenticated/activos.index'
import { Route as AuthenticatedActivosIdRouteImport } from './routes/_authenticated/activos.$id'
import { Route as ApiPublicVibrationIngestRouteImport } from './routes/api/public/vibration-ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdenesRoute = AuthenticatedOrdenesRouteImport.update({
  id: '/ordenes',
  path: '/ordenes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreventivoRoute = AuthenticatedPreventivoRouteImport.update({
  id: '/preventivo',
  path: '/preventivo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivosIndexRoute =
  AuthenticatedActivosIndexRouteImport.update({
    id: '/activos/',
    path: '/activos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivosIdRoute = AuthenticatedActivosIdRouteImport.update({
  id: '/activos/$id',
  path: '/activos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicVibrationIngestRoute =
  ApiPublicVibrationIngestRouteImport.update({
    id: '/api/public/vibration-ingest',
    path: '/api/public/vibration-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ordenes': typeof AuthenticatedOrdenesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/preventivo': typeof AuthenticatedPreventivoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/activos/$id': typeof AuthenticatedActivosIdRoute
  '/api/public/vibration-ingest': typeof ApiPublicVibrationIngestRoute
  '/activos/': typeof AuthenticatedActivosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ordenes': typeof AuthenticatedOrdenesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/preventivo': typeof AuthenticatedPreventivoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/activos/$id': typeof AuthenticatedActivosIdRoute
  '/api/public/vibration-ingest': typeof ApiPublicVibrationIngestRoute
  '/activos': typeof AuthenticatedActivosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ordenes': typeof AuthenticatedOrdenesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/preventivo': typeof AuthenticatedPreventivoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/activos/$id': typeof AuthenticatedActivosIdRoute
  '/api/public/vibration-ingest': typeof ApiPublicVibrationIngestRoute
  '/_authenticated/activos/': typeof AuthenticatedActivosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ordenes'
    | '/panel'
    | '/preventivo'
    | '/usuarios'
    | '/activos/$id'
    | '/api/public/vibration-ingest'
    | '/activos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ordenes'
    | '/panel'
    | '/preventivo'
    | '/usuarios'
    | '/activos/$id'
    | '/api/public/vibration-ingest'
    | '/activos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ordenes'
    | '/_authenticated/panel'
    | '/_authenticated/preventivo'
    | '/_authenticated/usuarios'
    | '/_authenticated/activos/$id'
    | '/api/public/vibration-ingest'
    | '/_authenticated/activos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicVibrationIngestRoute: typeof ApiPublicVibrationIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ordenes': {
      id: '/_authenticated/ordenes'
      path: '/ordenes'
      fullPath: '/ordenes'
      preLoaderRoute: typeof AuthenticatedOrdenesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preventivo': {
      id: '/_authenticated/preventivo'
      path: '/preventivo'
      fullPath: '/preventivo'
      preLoaderRoute: typeof AuthenticatedPreventivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activos/': {
      id: '/_authenticated/activos/'
      path: '/activos'
      fullPath: '/activos/'
      preLoaderRoute: typeof AuthenticatedActivosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activos/$id': {
      id: '/_authenticated/activos/$id'
      path: '/activos/$id'
      fullPath: '/activos/$id'
      preLoaderRoute: typeof AuthenticatedActivosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/vibration-ingest': {
      id: '/api/public/vibration-ingest'
      path: '/api/public/vibration-ingest'
      fullPath: '/api/public/vibration-ingest'
      preLoaderRoute: typeof ApiPublicVibrationIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrdenesRoute: typeof AuthenticatedOrdenesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPreventivoRoute: typeof AuthenticatedPreventivoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedActivosIdRoute: typeof AuthenticatedActivosIdRoute
  AuthenticatedActivosIndexRoute: typeof AuthenticatedActivosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrdenesRoute: AuthenticatedOrdenesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPreventivoRoute: AuthenticatedPreventivoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedActivosIdRoute: AuthenticatedActivosIdRoute,
  AuthenticatedActivosIndexRoute: AuthenticatedActivosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicVibrationIngestRoute: ApiPublicVibrationIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
